spring:
  application:
    name: finale
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/stock_test
        username: stcok_test
        password: big181234
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
server:
  port: 8028
  servlet:
    encoding:
        force: true
