spring:
  application:
    name: finale
#    datasource:
#        url: jdbc:mariadb://localhost:3306/big18
#        username: root
#        password: big181234
#        driver-class-name: org.mariadb.jdbc.Driver
#    jpa:
#        hibernate:
#            ddl-auto: update
#        show-sql: true
server:
  port: 8028
  servlet:
    encoding:
        force: true
